blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: mailto:security@yourproject.com
    about: Please report security vulnerabilities privately via email
  - name: Community Support
    url: https://github.com/yourusername/yourproject/discussions
    about: Please ask and answer questions in our community discussions
  - name: Documentation
    url: https://yourproject.com/docs
    about: Check our documentation for guides and FAQs