name: Documentation Issue
description: Report issues or suggest improvements for documentation
title: "[DOCS] "
labels: ["docs", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Report errors, unclear sections, or suggest new content.
        
  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation is this about?
      options:
        - User Guide
        - API Documentation
        - Installation Guide
        - FAQ
        - Tutorial
        - Other
    validations:
      required: true
      
  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: |
        Where in the documentation did you find this issue?
        Provide a URL or section name if possible.
      placeholder: "e.g., Getting Started > Installation"
      
  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of issue is this?
      options:
        - Incorrect information
        - Missing information
        - Unclear explanation
        - Broken link
        - Outdated content
        - Grammar/spelling error
        - New documentation needed
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the issue with the documentation
      placeholder: "The documentation states... but it should be..."
    validations:
      required: true
      
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: |
        How would you improve this documentation?
        If possible, provide the corrected text.
      placeholder: "I suggest changing it to..."
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context, such as:
        - Screenshots of the confusing section
        - Links to related issues
        - Examples that would help
        
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have verified this issue exists in the latest documentation
          required: true
        - label: I have provided a clear description and suggestion
          required: true