name: Question / Support
description: Ask a question or request help
title: "[QUESTION] "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Need help? Ask your question here! Please provide as much context as possible.
        
        **Note:** For general discussions, consider using our [Discussions](https://github.com/yourusername/yourproject/discussions) forum instead.
        
  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - How to use a feature
        - Installation / Setup
        - Configuration
        - Integration
        - Best practices
        - Troubleshooting
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform is your question about?
      multiple: true
      options:
        - Android
        - iOS
        - Desktop
        - Web
        - All platforms
        - Not platform-specific
    validations:
      required: true
      
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: "How do I..."
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Provide any relevant context:
        - What are you trying to achieve?
        - What have you already tried?
        - Are you following any specific guide or tutorial?
      placeholder: "I'm trying to... I've already attempted..."
    validations:
      required: true
      
  - type: textarea
    id: attempted
    attributes:
      label: What I've Tried
      description: |
        List any solutions or approaches you've already attempted.
        This helps us avoid suggesting things you've already done.
      placeholder: |
        - Checked the documentation for...
        - Tried to...
        - Searched for...
        
  - type: input
    id: version
    attributes:
      label: App Version
      description: What version are you using? (if applicable)
      placeholder: "e.g., 1.2.3"
      
  - type: textarea
    id: references
    attributes:
      label: Related Resources
      description: |
        Include any relevant:
        - Documentation links you've consulted
        - Error messages
        - Screenshots
        - Code snippets (properly formatted)
        
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have checked the documentation and FAQ
          required: true
        - label: I have provided enough context for others to understand my question
          required: true