name: Welcome New Contributors

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check if first issue
        id: first_issue
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.issue.user.login;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Get all issues created by this user
            const issues = await github.rest.issues.listForRepo({
              owner: owner,
              repo: repo,
              creator: creator,
              state: 'all'
            });
            
            // Check if this is their first issue (only one issue in the list)
            const isFirstIssue = issues.data.length === 1;
            core.setOutput('is_first', isFirstIssue);
            
      - name: Welcome first time contributor
        if: steps.first_issue.outputs.is_first == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const welcomeMessage = `👋 Welcome @${issue.user.login}! 
            
            Thank you for taking the time to report this issue. This appears to be your first issue in this repository - we're excited to have you here!
            
            **What happens next:**
            - Our team will review and triage this issue
            - We'll add appropriate labels and priority
            - You'll be notified of any updates or questions
            
            **While you wait:**
            - Check out our [documentation](https://yourproject.com/docs)
            - Browse other [open issues](https://github.com/${context.repo.owner}/${context.repo.repo}/issues) to see if you can help
            - Join our [community discussions](https://github.com/${context.repo.owner}/${context.repo.repo}/discussions)
            
            Thanks again for contributing to making our project better! 🎉`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: welcomeMessage
            });